USE DBVENTAS_WEB
GO

-- Verificar las tablas relacionadas con menús que existen
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME LIKE '%MENU%' OR TABLE_NAME LIKE '%SUB%'
ORDER BY TABLE_NAME
GO

-- Verificar todas las tablas de la base de datos
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME
GO
