USE DBVENTAS_WEB
GO

PRINT '========================================='
PRINT 'VERIFICANDO ESTRUCTURA REAL DE TABLAS'
PRINT '========================================='
PRINT ''

-- Verificar estructura de MENU
PRINT '--- ESTRUCTURA DE TABLA MENU ---'
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MENU'
ORDER BY ORDINAL_POSITION
GO

PRINT ''
PRINT '--- ESTRUCTURA DE TABLA SUBMENU ---'
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SUBMENU'
ORDER BY ORDINAL_POSITION
GO

PRINT ''
PRINT '--- ESTRUCTURA DE TABLA ROL ---'
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ROL'
ORDER BY ORDINAL_POSITION
GO

PRINT ''
PRINT '--- ESTRUCTURA DE TABLA USUARIO ---'
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'USUARIO'
ORDER BY ORDINAL_POSITION
GO

PRINT ''
PRINT '--- BUSCAR TABLA DE PERMISOS (MENU_ROL o similar) ---'
SELECT 
    TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%MENU%' OR TABLE_NAME LIKE '%ROL%' OR TABLE_NAME LIKE '%PERMISO%'
ORDER BY TABLE_NAME
GO

PRINT ''
PRINT '--- DATOS ACTUALES DE MENU ---'
SELECT TOP 5 * FROM MENU
GO

PRINT ''
PRINT '--- DATOS ACTUALES DE SUBMENU ---'
SELECT TOP 5 * FROM SUBMENU
GO

PRINT ''
PRINT '--- DATOS ACTUALES DE ROL ---'
SELECT * FROM ROL
GO

PRINT ''
PRINT '--- DATOS ACTUALES DE USUARIO ---'
SELECT TOP 5 * FROM USUARIO
GO

PRINT ''
PRINT '========================================='
PRINT 'VERIFICACION COMPLETADA'
PRINT '========================================='
PRINT ''
PRINT 'Copia TODOS los resultados y compártelos'
PRINT ''
