USE DBVENTAS_WEB
GO

PRINT '========================================='
PRINT 'COLUMNAS DE LA TABLA PROVEEDOR'
PRINT '========================================='
PRINT ''

SELECT 
    COLUMN_NAME AS Columna,
    DATA_TYPE AS Tipo,
    CHARACTER_MAXIMUM_LENGTH AS Longitud,
    IS_NULLABLE AS Nulo
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PROVEEDOR'
ORDER BY ORDINAL_POSITION
GO

PRINT ''
PRINT '--- DATOS DE EJEMPLO ---'
SELECT TOP 3 * FROM PROVEEDOR
GO
